// How to print In JS .................

console.log(" Hello World ")
// Console.log print karne ka kaam karte hai ... 

// alert ("This is a Web popup msg")
// alert .. ye serf DOM ..meens Chrome per hcalge web per chalega ... 

